name: neat
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.6.1=h7f98852_0
  - attr=2.5.1=h166bdaf_0
  - biopython=1.79=py310h5764c6d_2
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.6.15=ha878542_0
  - cachecontrol=0.12.11=pyhd8ed1ab_0
  - cachy=0.3.0=py_0
  - certifi=2022.6.15=py310hff52083_0
  - cffi=1.15.0=py310h0fdd8cc_0
  - cleo=0.8.1=pyhd8ed1ab_2
  - clikit=0.6.2=pyh9f0ad1d_0
  - crashtest=0.3.1=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - distlib=0.3.4=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fftw=3.3.10=nompi_h77c792f_102
  - filelock=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py310h5764c6d_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.70.2=h780b84a_4
  - glib-tools=2.70.2=h780b84a_4
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - jack=0.125.0=hf484d3e_1001
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - keyring=23.6.0=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.3=py310hbf28c38_0
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=15_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=15_linux64_openblas
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=hf5a7f15_1
  - libdb=6.1.26=0
  - libdeflate=1.12=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.70.2=h174f98d_4
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=15_linux64_openblas
  - libllvm14=14.0.6=he0ac6c6_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.4=hd77ab85_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=hc85c160_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_0
  - libzlib=1.2.12=h166bdaf_1
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.5.2=py310hff52083_0
  - matplotlib-base=3.5.2=py310h5701ce4_0
  - msgpack-python=1.0.4=py310hbf28c38_0
  - munkres=1.0.7=py_1
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - ncurses=6.3=h27087fc_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.0=py310h53a5b5f_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1p=h166bdaf_0
  - packaging=20.9=pyh44b312d_0
  - pastel=0.2.1=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pillow=9.1.1=py310he619898_1
  - pip=22.1.2=pyhd8ed1ab_0
  - pkginfo=1.8.3=pyhd8ed1ab_0
  - poetry=1.1.13=py310hff52083_1
  - poetry-core=1.0.8=py310hff52083_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=14.0=h583eb01_5
  - pycparser=2.21=pyhd8ed1ab_0
  - pylev=1.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.4=py310h29803b5_1
  - pysocks=1.7.1=py310hff52083_5
  - python=3.10.5=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyyaml=6.0=py310h5764c6d_4
  - pytest
  - qt-main=5.15.4=ha5833f6_2
  - readline=8.1.2=h0f457ee_0
  - requests-toolbelt=0.9.1=py_0
  - scipy=1.8.1=py310h7612f91_0
  - secretstorage=3.3.2=py310hff52083_1
  - setuptools=62.6.0=py310hff52083_0
  - shellingham=1.4.0=pyh44b312d_0
  - sip=6.5.1=py310h122e73d_2
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.0=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomlkit=0.11.0=pyha770c72_0
  - tornado=6.1=py310h5764c6d_3
  - typing=3.10.0.0=pyhd8ed1ab_0
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=h8a70e8d_2
  - pip:
    - asttokens==2.0.5
    - backcall==0.2.0
    - charset-normalizer==2.0.12
    - cryptography==37.0.3
    - decorator==5.1.1
    - executing==0.8.3
    - frozendict==2.3.4
    - ipython==8.4.0
    - jedi==0.18.1
    - matplotlib-inline==0.1.3
    - neat==4.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - platformdirs==2.5.2
    - prompt-toolkit==3.0.29
    - pure-eval==0.2.2
    - pygments==2.12.0
    - pyqt5-sip==12.9.0
    - pysam==0.19.1
    - requests==2.28.0
    - setuptools-scm==7.0.2
    - stack-data==0.3.0
    - tomli==2.0.1
    - traitlets==5.3.0
    - typing-extensions==4.2.0
    - virtualenv==20.15.0
    - wcwidth==0.2.5
prefix: /u/jallen17/.conda/envs/neat
