name: neat
channels:
    - conda-forge
    - bioconda

dependencies:
  - python=3.10.*
  - biopython=1.85
  - pkginfo
  - matplotlib
  - numpy
  - pyyaml
  - pip
  - scipy
  - libgcc=14
  - htslib
  - pip:
    - pysam
    - frozendict
    - poetry==1.3.*

  - pytest
