## Template for gen_reads parallel
## Any parameter that is not required but has a default value will use the
## default value even if the variable is not included in the config. For
## required items, they must be included in the config and the must be given a value.
## All other items can be present or not. If present and the value is set to a single
## period, the variable will be treated as though it had been omitted. Please do
## not modify this template, but instead make a copy in your working directory. Done this
## way, you can run without even needing to declare -c.

<<<<<<< HEAD
# Absolute path to input reference fasta file
=======
# Absolute path to input reference fasta file_list
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# type = string | required: yes
reference: REQUIRED

# How to partition the reference for analysis. By default, NEAT will
# attempt to process one contig per thread. However, if you have very
# large fasta files, you will see additional runtime benefit from choosing
# the subdivision method, which will split the contigs up into equal sizes
# for processing. If you need further speedups and have access to a distributed system
# you can use a shell script wrapper around NEAT to split the fasta into
# contigs, then join the results later. NEAT does not feature translocations, so
# this will not affect NEAT's output. Note that subdivision will only activate for
# number of threads > 1.
# type = string | required: No | default = chrom | possible values: chrom, subdivision
partition_mode: .

# Read length of the reads in the fastq output. Only required if @produce_fastq is set to true
# type = int | required: no | default = 101
read_len: .

# Number of threads to request for NEAT. The recommended amount is the number of chromosomes in
# your input fasta plus 1.
# type = int | required: no | default = 1
threads: .

# Average Coverage for the entire genome.
# type = float | required: no | default = 10.0
coverage: .

<<<<<<< HEAD
# Absolute path to file with sequencing error model
=======
# Absolute path to file_list with sequencing error model
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# type = string | required: no | default: <NEAT_DIR>/neat/models/defaults/default_error_model.pickle.gz
error_model: .

# Average sequencing error rate for the sequencing machine
# type = float | required = no | must be between 0.0 and 0.3
avg_seq_error: .

# This scales the quality scores to match the desired average sequencing error rate
# specified by avg_seq_error.
# type: boolean | required = no | default = false
rescale_qualities: .

# This is the factor to add to the quality scores to get the ascii text version of the
# score. The default follows the sanger quality offset
# type: int | required = no | default = 33
quality_offset: .

# Desired ploidy
# type = int | required = no | default = 2
ploidy: .

<<<<<<< HEAD
# Absolute path to vcf file containing variants that will always be included, regardless
=======
# Absolute path to vcf file_list containing variants that will always be included, regardless
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# of genotype and filter. You can pre-filter your vcf for these fields before inputting it
# if this is not the desired behavior.
# type: string | required = no
input_variants: .

<<<<<<< HEAD
# Absolute path to bed file containing reference regions that the simulation
=======
# Absolute path to bed file_list containing reference regions that the simulation
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# should target.
# type = string | required = no
target_bed: .

# Scalar value for coverage in regions outside the targeted bed. Example 0.5
# would get you roughly half the coverage as the on target areas. Default is
# 2% of total coverage in off-target regions.
# type: float | required = no | default = 0.02
off_target_scalar: .

# Whether to discard areas outside the targeted bed region. By default, this is set
# to false and NEAT will use a different model for off-target regions but still
# include them in the final output.
# TODO this may not be necessary
# type: boolean | required = no | default = false
discard_offtarget: .

<<<<<<< HEAD
# Absolute path to bed file containing reference regions that the simulation
=======
# Absolute path to bed file_list containing reference regions that the simulation
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# should discard.
# type = string | required = no
discard_bed: .

<<<<<<< HEAD
# Absolute path to the mutation model pickle file. Omitting this value will cause
=======
# Absolute path to the mutation model pickle file_list. Omitting this value will cause
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# NEAT to use the default model, with some standard parameters, and generally uniform biases.
# type: string | required = no
mutation_model: .

# Average mutation rate per base pair. Overall average is 0.001, or model default
# Use either this value to override the mutation rate for the default or input model.
# type: float | required = no | must be between 0.0 and 0.3
mutation_rate: .

<<<<<<< HEAD
# Absolute path to a bed file with mutation rates by region.
=======
# Absolute path to a bed file_list with mutation rates by region.
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# Rates must be in the fourth column and be of the form "mut_rate=x.xx"
# Rates must be between 0.00 and 0.03
# type: string | required = no
mutation_bed: .

# Absolute path to GC content model generated by compute_gc.py
# type: string | required = no | default: <NEAT_DIR>/neat/models/defaults/default_gc_bias_model.pickle.gz
gc_model: .

# Whether the output should be paired ended. For certain conditions (i.e., vcf only or
# fasta only), this will be ignored. If this is true, then there must be an included fragment
# length model output from runner.py or a mean and standard deviation
# by declaring values for @fragment_mean and @fragment_std_dev.
# type: boolean | required = no | default = false
paired_ended: .

<<<<<<< HEAD
# Absolute path to a pickle file containing the fragment length model output
=======
# Absolute path to a pickle file_list containing the fragment length model output
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# from runner.py.
# type: string | required = no | default: <NEAT_DIR>/neat/models/defaults/default_fraglen_model.pickle.gz
fragment_model: .

# Mean for the paired end fragment length. This only applies if paired-ended is set to true.
# This number will form the mean for the sample distribution of the fragment lengths in the simulation
# Note: This number is REQUIRED if paired_ended is set to true, unless a fragment length model is used.
# type: float | required: no (unless paired-ended)
fragment_mean: .

# Standard deviation for the paired end fragment length. This only applies if paired-ended is set to true.
# This number will form the standard deviation about the mean specified above for the sample distribution
# of the fragment lengths in the simulation.
# Note: This number is REQUIRED if paired_ended is set to true, unless a fragment length model is used.
# type: float | required: no (unless paired-ended)
fragment_st_dev: .

<<<<<<< HEAD
# Whether to produce the golden bam file. This file will contain the reads
=======
# Whether to produce the golden bam file_list. This file_list will contain the reads
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# aligned with the exact region of the genome
# type: boolean | required = no | default = false
produce_bam: .

<<<<<<< HEAD
# Whether to produce a vcf file containing all the mutation errors added
=======
# Whether to produce a vcf file_list containing all the mutation errors added
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# by NEAT.
# type: boolean | required = no | default = false
produce_vcf: .

<<<<<<< HEAD
# Whether to output the mutated fasta. This will output a fasta file with mutations
=======
# Whether to output the mutated fasta. This will output a fasta file_list with mutations
>>>>>>> 5d3b24e267938502bbd68617dafca289f2135e02
# inserted. It does not include sequencing errors or read information. Useful for
# multigenerational mutations.
# type: boolean | required = no | default = false
produce_fasta: .

# Whether to output the fastq(s) of the reads. This is the default output. NEAT
# will produce 1 fastq for single ended reads or 2 fastqs for paired ended.
# type: boolean | required = no | default = true
produce_fastq: .

# If set to true, this will ignore statistical models and force coverage to be
# constant across the genome. This is considered a debugging feature.
# type: boolean | required = no | default = false
no_coverage_bias: .

# Set an RNG seed value. Runs using identical RNG values should produce identical results
# so things like read locations, variant positions, error positions, etc. should be the same.
# Useful for debugging.
# type: int | required = no
rng_seed: .

# Set an absolute minimum number of mutations. The program always adds at least 1 mutation.
# Useful for very small datasets.
# type: int | required = no
min_mutations: .

# If you would like to produce 1 fasta per ploid, set this value to true.
# Otherwise NEAT will attempt to write them all to one fasta (which may result in some data loss)
# type: bool | required = no | default = false
fasta_per_ploid: .