name: CI for Utilities
on:
  pull_request:
    paths:
      - '!utilities/**'
      
jobs:
  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
      
  job-valBAM:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Execute validateBAM.py
        run: |
          cd ${{ github.workspace }}/utilities
          python validateBam.py -i ../sample_data/baby.bam
      - run: echo "üçè This job's status is ${{ job.status }}."
      
  job-valFQ:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Execute validateFQ.py
        run: |
           pip install biopython
           cd ${{ github.workspace }}/utilities
           python validateFQ.py -i ../sample_data/baby.fastq
      - run: echo "üçè This job's status is ${{ job.status }}."

  job-genmut:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Execute gen_mut_model.py
         run: |
           pip install numpy
           pip install biopython
           pip install pandas
           cd ${{ github.workspace }}/utilities
           python gen_mut_model.py -r ../sample_data/ecoli.fa -m ../sample_data/small.vcf -o testgmm  
       - run: echo "üçè This job's status is ${{ job.status }}."

  job-computegc:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Execute compute_gc.py
         run: |
           pip install numpy
           pip install biopython
           pip install pandas
           cd ${{ github.workspace }}/utilities
           python compute_gc.py -i ../sample_data/small.genomecov -r ../sample_data/ecoli.fa -o gcop  
       - run: echo "üçè This job's status is ${{ job.status }}."

  job-genSeq:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Execute genSeqErrorModel.py
         run: |
           pip install numpy
           pip install biopython
           pip install pandas
           pip install matplotlib
           pip install pysam
           cd ${{ github.workspace }}/utilities
           python genSeqErrorModel.py -i ../sample_data/baby.fastq -o genseop2
       - run: echo "üçè This job's status is ${{ job.status }}."
